{{- if and .Values.networkPolicies.enabled .Values.upstream.serviceMonitor.enabled (and (ne .Release.Namespace "grafana") (ne .Release.Namespace "monitoring")) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Values.upstream.nameOverride }}
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: monitoring
        podSelector:
          matchLabels:
            app: prometheus
    - ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
{{- end }}
