{{ if and .Values.networkPolicies.enabled (and (ne .Release.Namespace "grafana") (ne .Release.Namespace "monitoring")) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
{{- end }}
