{{- $namespace := "backstage" }}
{{- $ns := lookup "v1" "Namespace" .Release.Namespace $namespace }}
{{- if and $ns  .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-backstage-app-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: backstage
      podSelector:
        matchLabels:
          app.kubernetes.io/name: backstage
    ports:
    - port: 3000
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
{{- end }}
