{{- if and .Values.networkPolicies.enabled .Values.istio.enabled (and (ne .Release.Namespace "grafana") (ne .Release.Namespace "monitoring")) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-istio-ingressgateway-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          {{- if .Values.networkPolicies.istioNamespaceSelector }}
          app.kubernetes.io/name: {{ .Values.networkPolicies.istioNamespaceSelector.ingress }}
          {{- else }}
          app.kubernetes.io/name: "istio-controlplane"
          {{- end }}
      podSelector:
        matchLabels:
          {{- toYaml .Values.networkPolicies.ingressLabels | nindent 10}}
    ports:
    - port: {{ .Values.service.targetPort }}
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
{{- end }}
