{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: shared-grafana-authz-policy
  namespace: {{ .Values.istio.namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - {{ .Release.Namespace }}
        principals:
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ template "grafana.serviceAccountName" . }}
{{- end }}
