{{- if include "grafana.shouldDeployUpgradeResources" . }}
{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ .Release.Name }}-upgrade-api
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  podSelector:
    matchLabels:
      batch.kubernetes.io/job-name: {{ .Release.Name }}-upgrade
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        # ONLY Block requests to cloud metadata IP
        except:
        - 169.254.169.254/32
{{- end }}
{{- end }}