{{- if include "grafana.shouldDeployUpgradeResources" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-upgrade-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- end }}