{{- if .Values.enterprise.createSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-enterprise-license
  namespace: "{{ .Release.Namespace }}"
data:
  license.jwt: {{ .Values.enterprise.license | b64enc | quote }}
{{- end }}