{{- if and .Values.istio.enabled (eq .Values.istio.injection "enabled") (ne .Release.Namespace "monitoring") }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default-grafana
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
{{- end }}
