{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.kiali.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "grafana-kiali-authz-policy"
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" $ | nindent 6 }} 
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.kiali.namespaces | toYaml | nindent 10 }}
        principals: {{ .Values.istio.hardened.kiali.principals | toYaml | nindent 10 }}
{{- end }}